--%carp-begin
create or replace force view PEV_T_LOV_PROJECT_STATUS_API as
select "ID", "STATUS_NAME", "STATUS_TYPE", "IS_DELETED", "CREATED_DATE", "CREATED_BY", "UPDATED_DATE", "UPDATED_BY"
 from PEV_T_LOV_PROJECT_STATUS
/
show errors


COMMENT ON TABLE PEV_T_LOV_PROJECT_STATUS_API IS 'Ciselnik pro statusy projektu'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATUS_API.ID IS 'PK - ID Identifikátor'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATUS_API.STATUS_NAME IS 'Název statusu'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATUS_API.STATUS_TYPE IS 'Typ statusu ( P - projekt, null - detail )'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATUS_API.IS_DELETED IS 'Příznak smazání záznamu (1 - smazán)'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATUS_API.CREATED_DATE IS 'datum vytvoření'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATUS_API.CREATED_BY IS 'Uživatel, který vytvoril záznam.'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATUS_API.UPDATED_DATE IS 'datum ulozeni'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATUS_API.UPDATED_BY IS 'Uživatel, který uložil záznam.'
/

--%carp-end
