--%carp-begin
create or replace force view PEV_T_LOV_PROJECT_IDENTIFY_API as
select "ID", "NAME", "IS_DELETED", "CREATED_DATE", "CREATED_BY", "UPDATED_DATE", "UPDATED_BY"
 from PEV_T_LOV_PROJECT_IDENTIFY
/
show errors


COMMENT ON TABLE PEV_T_LOV_PROJECT_IDENTIFY_API IS 'Ciselnik pro identifikace projektu'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_IDENTIFY_API.ID IS 'PK - ID Identifikátor'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_IDENTIFY_API.NAME IS 'Identifikační Název'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_IDENTIFY_API.IS_DELETED IS 'Příznak smazání záznamu (1 - smazán)'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_IDENTIFY_API.CREATED_DATE IS 'datum vytvoření'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_IDENTIFY_API.CREATED_BY IS 'Uživatel, který vytvoril záznam.'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_IDENTIFY_API.UPDATED_DATE IS 'datum ulozeni'
/

COMMENT ON COLUMN PEV_T_LOV_PROJECT_IDENTIFY_API.UPDATED_BY IS 'Uživatel, který uložil záznam.'
/

--%carp-end
