--%carp-begin
create or replace force view PEV_T_PROJECT_LOGBOOK_API as
select "RECORD_ID", "PROJECT_ID", "RECORD_DATE", "TEXT", "IS_DELETED", "CREATED_DATE", "CREATED_BY", "UPDATED_DATE",
    "UPDATED_BY"
 from PEV_T_PROJECT_LOGBOOK
/
show errors


COMMENT ON TABLE PEV_T_PROJECT_LOGBOOK_API IS 'Journal table.'
/

COMMENT ON COLUMN PEV_T_PROJECT_LOGBOOK_API.RECORD_ID IS 'Primary key id'
/

COMMENT ON COLUMN PEV_T_PROJECT_LOGBOOK_API.PROJECT_ID IS 'ID project foreign key'
/

COMMENT ON COLUMN PEV_T_PROJECT_LOGBOOK_API.RECORD_DATE IS 'date of record'
/

COMMENT ON COLUMN PEV_T_PROJECT_LOGBOOK_API.TEXT IS 'text message'
/

COMMENT ON COLUMN PEV_T_PROJECT_LOGBOOK_API.IS_DELETED IS 'deleted flag: 0 - valid, 1 - deleted'
/

COMMENT ON COLUMN PEV_T_PROJECT_LOGBOOK_API.CREATED_DATE IS 'date of creating record'
/

COMMENT ON COLUMN PEV_T_PROJECT_LOGBOOK_API.CREATED_BY IS 'autor of creating record'
/

COMMENT ON COLUMN PEV_T_PROJECT_LOGBOOK_API.UPDATED_DATE IS 'date of last change'
/

COMMENT ON COLUMN PEV_T_PROJECT_LOGBOOK_API.UPDATED_BY IS 'autor of last change'
/

--%carp-end
