--%carp-begin
create or replace force view PEV_T_PROJECTS_API as
select "ID", "NAME", "PROJECT_STATE", "IDENTIFICATION", "PROJECT_STATUS", "KAKADU_NUMBER", "BDC_NUMBER", "BDC_OPS",
    "DEPARTMENT","PROJECT_MANAGER", "BUSINESS_OWNER", "IT_OWNER", "START_DATE_EXPECT", "START_DATE_REAL",
    "END_DATE_EXP","END_DATE_REAL", "BUDGET", "FORECAST", "FORECAST_APPROVE_DATE", "PROJECT_DESCRIPTION", "DESCR_SCOPE",
    "LAYOUT","LAYOUT_URL", "IS_DELETED", "CREATED_DATE", "CREATED_BY", "UPDATED_DATE", "UPDATED_BY" , "BUDGET_APPROVE_DATE" , "BUDGET_APPROVE" , "FORECAST_APPROVE", "NOTE", "PROJECT_CHANGE", "APPROVE", "IS_DUPLICATED"
 from PEV_T_PROJECTS
/
show errors

 

COMMENT ON TABLE PEV_T_PROJECTS_API IS 'Tabulka projektů.'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.APPROVE IS  'Ke schválení - checkbox'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.ID IS 'PK - ID Identifikátor'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.NAME IS 'Jmeno projektu'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.PROJECT_STATE IS 'FK -state'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.IDENTIFICATION IS ' FK - identification'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.PROJECT_STATUS IS 'FK - Project status'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.KAKADU_NUMBER IS 'kakadu číslo'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.BDC_NUMBER IS 'bdc_number specifikace'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.BDC_OPS IS 'bdc_ops specifikace'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.DEPARTMENT IS 'ID_Lekarny - select list 900-999'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.PROJECT_MANAGER IS 'FK - peoples'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.BUSINESS_OWNER IS 'FK - peoples'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.IT_OWNER IS 'FK - peoples'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.START_DATE_EXPECT IS 'Očekavaný start'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.START_DATE_REAL IS 'Reální start'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.END_DATE_EXP IS 'Očekavaný konec'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.END_DATE_REAL IS 'Reální konec'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.FORECAST IS 'Odhad'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.FORECAST_APPROVE_DATE IS 'Odhadovaný čas'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.PROJECT_DESCRIPTION IS 'Popis'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.DESCR_SCOPE IS 'Popis oblasti'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.LAYOUT IS 'Navrh 1/0'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.LAYOUT_URL IS 'Navrh url'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.IS_DELETED IS 'Příznak smazání záznamu (1 - smazán)'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.CREATED_DATE IS 'datum vytvoření'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.CREATED_BY IS 'Uživatel, který vytvoril záznam.'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.UPDATED_DATE IS 'datum ulozeni'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.UPDATED_BY IS 'Uživatel, který uložil záznam.'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.BUDGET_APPROVE_DATE IS 'Odhadovaný čas'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.BUDGET_APPROVE IS 'Osaba ktora schvalila budget'
/

COMMENT ON COLUMN PEV_T_PROJECTS_API.FORECAST_APPROVE IS 'Osaba ktora schvalila forecast'
/
COMMENT ON COLUMN PEV_T_PROJECTS_API.NOTE IS 'Poznámka'
/
COMMENT ON COLUMN PEV_T_PROJECTS_API.PROJECT_CHANGE IS 'Poslední změna na projektu'
/
COMMENT ON COLUMN PEV_T_PROJECTS_API.IS_DUPLICATED IS 'Jesli vyšel z kopie 1-ano, 2 byl zaslan mail'
/

--%carp-end
