  GRANT SELECT ON "CEOS_INTRADM"."PEV_T_NOTE_REMIDER_LOG" TO "CEOS_INTRADM_APEX" WITH GRANT OPTION
  /
  GRANT INSERT ON "CEOS_INTRADM"."PEV_T_NOTE_REMIDER_LOG" TO "CEOS_INTRADM_APEX" WITH GRANT OPTION
  /
  GRANT UPDATE ON "CEOS_INTRADM"."PEV_T_NOTE_REMIDER_LOG" TO "CEOS_INTRADM_APEX" WITH GRANT OPTION
  /
  GRANT DELETE ON "CEOS_INTRADM"."PEV_T_NOTE_REMIDER_LOG" TO "CEOS_INTRADM_APEX" WITH GRANT OPTION
  /