  GRANT SELECT ON "CEOS_INTRADM"."PEV_T_LOVE_REMIDER_API" TO "CEOS_INTRADM_APEX" WITH GRANT OPTION
  /
  GRANT INSERT ON "CEOS_INTRADM"."PEV_T_LOVE_REMIDER_API" TO "CEOS_INTRADM_APEX" WITH GRANT OPTION
  /
  GRANT UPDATE ON "CEOS_INTRADM"."PEV_T_LOVE_REMIDER_API" TO "CEOS_INTRADM_APEX" WITH GRANT OPTION
  /
  GRANT DELETE ON "CEOS_INTRADM"."pev_t_love_remider_API" TO "CEOS_INTRADM_APEX" WITH GRANT OPTION
  /