BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PEV_T_CHANGES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
CREATE TABLE PEV_T_CHANGES(
ID integer,
RECORD_ID integer,
CAT varchar(20 CHAR),      -- PROJECT/DEVELOPER/PEOPLE
CAT_ID integer,
ITEM varchar(50 CHAR),     -- NAME, SURNAME, ETC...
ITEM_ID integer,
OLD_VALUE varchar (1000 CHAR),
VALUE varchar (1000 CHAR),
ACTION VARCHAR(1 CHAR),    --
CREATED_DATE DATE,
CREATED_BY VARCHAR2(30 CHAR),
UPDATED_DATE DATE,
UPDATED_BY VARCHAR2(30 CHAR),
CONSTRAINT PK_CHANGES PRIMARY KEY (id)
);
COMMENT ON TABLE PEV_T_CHANGES IS 'Tabulka provedených změn na projektové evidenci';
COMMENT ON COLUMN PEV_T_CHANGES.UPDATED_DATE IS 'Datum ulozeni';
COMMENT ON COLUMN PEV_T_CHANGES.UPDATED_BY IS 'Uživatel, který uložil záznam.';
COMMENT ON COLUMN PEV_T_CHANGES.CREATED_DATE IS 'Datum vytvoření';
COMMENT ON COLUMN PEV_T_CHANGES.CREATED_BY IS 'Uživatel, který vytvoril záznam.';
COMMENT ON COLUMN PEV_T_CHANGES.id IS 'PK - ID Identifikátor - triggerem z pev_s_changes';
COMMENT ON COLUMN PEV_T_CHANGES.RECORD_ID IS 'ID celého záznamu. Bere z pev_s_changes_record';
COMMENT ON COLUMN PEV_T_CHANGES.CAT IS 'Kategorie PROJECT/PROJEKT_DEVELOPER';
COMMENT ON COLUMN PEV_T_CHANGES.CAT_ID IS 'ID projektu';
COMMENT ON COLUMN PEV_T_CHANGES.ITEM IS 'Položka';
COMMENT ON COLUMN PEV_T_CHANGES.ITEM_ID IS 'Použiváno pro detail na id developera';
COMMENT ON COLUMN PEV_T_CHANGES.OLD_VALUE IS 'Původní hodnotaa';
COMMENT ON COLUMN PEV_T_CHANGES.VALUE IS 'Nová hodnota';
COMMENT ON COLUMN PEV_T_CHANGES.ACTION IS 'I, U, D -- insert, update, delete';
/
