BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PEV_T_PEOPLE_POSITIONS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/
CREATE TABLE PEV_T_PEOPLE_POSITIONS(
PEOPLE_ID           integer,
POSITION_ID              integer,
CREATED_DATE        DATE,
CREATED_BY          VARCHAR2(30 CHAR),
UPDATED_DATE        DATE,
UPDATED_BY          VARCHAR2(30 CHAR),
CONSTRAINT FK_PEOPLES_POSITIONS
    FOREIGN KEY (position_id)
    REFERENCES PEV_T_LOV_PEOPLE_POSITION(id),
CONSTRAINT FK_POSITIONS_PEOPLES
    FOREIGN KEY (people_id)
    REFERENCES PEV_T_PEOPLES(id),
CONSTRAINT PK_PEV_T_PEOPLE_POSITIONS primary key (people_id, position_id)
);
COMMENT ON TABLE PEV_T_PEOPLE_POSITIONS IS 'Vazebnní tabulka člověk - pozice.';
COMMENT ON COLUMN PEV_T_PEOPLE_POSITIONS.people_id IS 'FK - ID člověka';
COMMENT ON COLUMN PEV_T_PEOPLE_POSITIONS.position_id IS 'FK - project';
COMMENT ON COLUMN PEV_T_PEOPLE_POSITIONS.UPDATED_DATE IS 'datum ulozeni';
COMMENT ON COLUMN PEV_T_PEOPLE_POSITIONS.UPDATED_BY IS 'Uživatel, který uložil záznam.';
COMMENT ON COLUMN PEV_T_PEOPLE_POSITIONS.CREATED_DATE IS 'datum vytvoření';
COMMENT ON COLUMN PEV_T_PEOPLE_POSITIONS.CREATED_BY IS 'Uživatel, který vytvoril záznam.';
/

