BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PEV_T_PROFILE_OPTIONS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

CREATE TABLE "PEV_T_PROFILE_OPTIONS"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CODE" VARCHAR2(30 BYTE),
	"VALUE" VARCHAR2(1000 BYTE),
	"CREATED_BY" VARCHAR2(30 BYTE),
	"LAST_UPDATE_BY" VARCHAR2(30 BYTE),
	"CREATED_DATE" DATE,
	"LAST_UPDATE_DATE" DATE,
	 CONSTRAINT "PEV_PROFILE_OPTIONS_PK" PRIMARY KEY ("ID")
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
/
