
  CREATE TABLE "PEV_T_LOVE_REMIDER"
   ("ID" NUMBER,
    "NAME" VARCHAR2(50 CHAR),
	"NOTE_ICON" VARCHAR2(25 CHAR),
	"NOTE_ICON_COLOR" VARCHAR2(25 CHAR),
	"NOTE_HEADER" VARCHAR2(255 CHAR),
	"NOTE_TEXT" VARCHAR2(500 CHAR),
	"NOTE_COLOR" VARCHAR2(25 CHAR),
	"CREATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE
   )
   
     CREATE SEQUENCE  "CEOS_INTRADM_BL"."PEV_S_LOVE_REMIDER"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 15368 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
  
   COMMENT ON COLUMN "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER"."ID" IS 'PK pro note remider log ze PEV_S_LOVE_REMIDER';
   COMMENT ON COLUMN "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER"."NOTE_ICON" IS 'class for awesome icons for example "fa-exclamation-triangle"';
   COMMENT ON COLUMN "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER"."NAME" IS 'Name of reminder';
   COMMENT ON COLUMN "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER"."NOTE_ICON_COLOR" IS 'colour for awesome icons for example "rgb(192,0,15)"';
   COMMENT ON COLUMN "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER"."NOTE_HEADER" IS 'header text of notification';
   COMMENT ON COLUMN "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER"."NOTE_TEXT" IS 'body html text for notification';
   COMMENT ON COLUMN "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER"."NOTE_COLOR" IS 'colour for notofication entry "rgb(192,0,15)"';
   COMMENT ON COLUMN "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER"."CREATE_DATE" IS 'datum vyvoreni';
   COMMENT ON TABLE "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER"  IS 'Tabulka notifikaci';


  GRANT SELECT ON "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER" TO "CEOS_INTRADM" WITH GRANT OPTION;
  GRANT INSERT ON "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER" TO "CEOS_INTRADM" WITH GRANT OPTION;
  GRANT UPDATE ON "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER" TO "CEOS_INTRADM" WITH GRANT OPTION;
  GRANT DELETE ON "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER" TO "CEOS_INTRADM" WITH GRANT OPTION;
  GRANT READ ON "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER" TO "CEOS_INTRADM" WITH GRANT OPTION;
  GRANT READ ON "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER" TO "RL_CEOS_INTRADM_BL_RO";


  create or replace synonym PEV_T_LOVE_REMIDER for CEOS_INTRADM_BL.PEV_T_LOVE_REMIDER
  
  
  create or replace synonym PEV_T_LOVE_REMIDER for CEOS_INTRADM_BL.PEV_T_LOVE_REMIDER
  
  
   --%carp-begin
create or replace force view PEV_T_LOVE_REMIDER_API as
select "ID", "NAME", "NOTE_ICON", "NOTE_ICON_COLOR", "NOTE_HEADER", "NOTE_TEXT",
    "NOTE_COLOR",  "CREATE_DATE"
 from PEV_T_LOVE_REMIDER
/
show errors


COMMENT ON TABLE PEV_T_LOVE_REMIDER_API IS 'Tabulka notifikaci'
/

COMMENT ON COLUMN PEV_T_LOVE_REMIDER_API.ID IS 'PK pro note remider log ze CPM_S_NOTE_REMIDER_LOG'
/

COMMENT ON COLUMN PEV_T_LOVE_REMIDER_API.NOTE_ICON IS 'class for awesome icons for example "fa-exclamation-triangle"'
/

COMMENT ON COLUMN PEV_T_LOVE_REMIDER_API.NOTE_ICON_COLOR IS 'colour for awesome icons for example "rgb(192,0,15)"'
/

COMMENT ON COLUMN PEV_T_LOVE_REMIDER_API.NOTE_HEADER IS 'header text of notification'
/

COMMENT ON COLUMN PEV_T_LOVE_REMIDER_API.NOTE_TEXT IS 'body html text for notification'
/

COMMENT ON COLUMN PEV_T_LOVE_REMIDER_API.NOTE_COLOR IS 'colour for notofication entry "rgb(192,0,15)"'
/

COMMENT ON COLUMN PEV_T_LOVE_REMIDER_API.CREATE_DATE IS 'datum vyvoreni'
/

COMMENT ON COLUMN PEV_T_LOVE_REMIDER_API.NAME IS 'Name of reminder'
/

--%carp-end





--%carp-begin
grant select on PEV_T_LOVE_REMIDER_API to CEOS_INTRADM_APEX with grant option
/

grant insert on PEV_T_LOVE_REMIDER_API to CEOS_INTRADM_APEX with grant option
/

grant update on PEV_T_LOVE_REMIDER_API to CEOS_INTRADM_APEX with grant option
/

grant delete on PEV_T_LOVE_REMIDER_API to CEOS_INTRADM_APEX with grant option
/

--%carp-end