COMMENT ON COLUMN PEV_T_PEOPLES.UPDATED_DATE IS 'Datum uložení';
COMMENT ON COLUMN PEV_T_PEOPLES.UPDATED_BY IS 'Uživatel, který uložil záznam';
COMMENT ON COLUMN PEV_T_PEOPLES.CREATED_DATE IS 'Datum vytvoření';
COMMENT ON COLUMN PEV_T_PEOPLES.CREATED_BY IS 'Uživatel, který vytvořil záznam';
COMMENT ON COLUMN PEV_T_PEOPLES.position IS 'FK - PEV_T_LOV_PEOPLE_POSITION(ID) - POSITION';








