ALTER TABLE PEV_T_PROJECTS ADD BUDGET_APPROVE NUMBER;

ALTER TABLE PEV_T_PROJECTS ADD FORECAST_APPROVE NUMBER;

COMMENT ON COLUMN PEV_T_PROJECTS.BUDGET_APPROVE
     IS 'LFK PEV_T_PEOPLES';
COMMENT ON COLUMN PEV_T_PROJECTS.FORECAST_APPROVE
     IS 'LFK PEV_T_PEOPLES';


