COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATUS.UPDATED_DATE IS 'Datum uložení';
COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATUS.UPDATED_BY IS 'Uživatel, který uložil záznam';
COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATUS.CREATED_DATE IS 'Datum vytvoření';
COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATUS.CREATED_BY IS 'Uživatel, který vytvořil záznam';








