COMMENT ON COLUMN PEV_T_LOV_PROJECT_IDENTIFY.UPDATED_DATE IS 'Datum uložení';
COMMENT ON COLUMN PEV_T_LOV_PROJECT_IDENTIFY.UPDATED_BY IS 'Uživatel, který uložil záznam';
COMMENT ON COLUMN PEV_T_LOV_PROJECT_IDENTIFY.CREATED_DATE IS 'Datum vytvoření';
COMMENT ON COLUMN PEV_T_LOV_PROJECT_IDENTIFY.CREATED_BY IS 'Uživatel, který vytvořil záznam';
COMMENT ON COLUMN PEV_T_LOV_PROJECT_IDENTIFY.id IS 'PK - ID Identifikátor';
COMMENT ON COLUMN PEV_T_LOV_PROJECT_IDENTIFY.name IS 'Identifikační název';
COMMENT ON COLUMN PEV_T_LOV_PROJECT_IDENTIFY.is_deleted IS 'Příznak smazání záznamu (1 - smazán)';








