COMMENT ON COLUMN PEV_T_LOV_PEOPLE_POSITION.UPDATED_DATE IS 'Datum uložení';
COMMENT ON COLUMN PEV_T_LOV_PEOPLE_POSITION.UPDATED_BY IS 'Uživatel, který uložil záznam';
COMMENT ON COLUMN PEV_T_LOV_PEOPLE_POSITION.CREATED_DATE IS 'Datum vytvoření';
COMMENT ON COLUMN PEV_T_LOV_PEOPLE_POSITION.CREATED_BY IS 'Uživatel, který vytvořil záznam';
COMMENT ON COLUMN PEV_T_LOV_PEOPLE_POSITION.id IS 'PK - ID Identifikátor';
COMMENT ON COLUMN PEV_T_LOV_PEOPLE_POSITION.name IS 'Název vlastníka';
COMMENT ON COLUMN PEV_T_LOV_PEOPLE_POSITION.is_deleted IS 'Příznak smazání záznamu (1 - smazán)';








