COMMENT ON COLUMN PEV_T_FILES.id IS 'ID';
COMMENT ON COLUMN PEV_T_FILES.UPDATED_DATE IS 'Datum uložení';
COMMENT ON COLUMN PEV_T_FILES.UPDATED_BY IS 'Uživatel, který uložil záznam';
COMMENT ON COLUMN PEV_T_FILES.CREATED_DATE IS 'Datum vytvoření';
COMMENT ON COLUMN PEV_T_FILES.CREATED_BY IS 'Uživatel, který vytvořil záznam';
COMMENT ON COLUMN PEV_T_FILES.FILE_NAME IS 'Název souboru';
COMMENT ON COLUMN PEV_T_FILES.FILE_MIME_TYPE IS 'Mime typ';
COMMENT ON COLUMN PEV_T_FILES.FILE_SIZE IS 'Velkost v bitech';
COMMENT ON COLUMN PEV_T_FILES.FILE_CONTENT IS 'Obsah souboru';
COMMENT ON COLUMN PEV_T_FILES.PROJECT_ID IS 'ID projektu';








