BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PEV_T_PEOPLES DROP CONSTRAINT "FK_PEOPLE_POSITION"';
  EXCEPTION WHEN others THEN
    null;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PEV_T_PEOPLES ADD CONSTRAINT "FK_PEOPLE_POSITION" FOREIGN KEY ("POSITION") REFERENCES "CEOS_INTRADM_BL"."PEV_T_LOV_PEOPLE_POSITION" ("ID") ENABLE';
  EXCEPTION WHEN others THEN
    null;
END;
/
