COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATE.UPDATED_DATE IS 'Datum uložení';
COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATE.UPDATED_BY IS 'Uživatel, který uložil záznam';
COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATE.CREATED_DATE IS 'Datum vytvoření';
COMMENT ON COLUMN PEV_T_LOV_PROJECT_STATE.CREATED_BY IS 'Uživatel, který vytvořil záznam';








