COMMENT ON TABLE PEV_T_PROFILE_OPTIONS IS 'Tabulka parametrů pro projektovou evidenci';
COMMENT ON COLUMN PEV_T_PROFILE_OPTIONS.LAST_UPDATE_DATE IS 'Datum uložení';
COMMENT ON COLUMN PEV_T_PROFILE_OPTIONS.LAST_UPDATE_BY IS 'Uživatel, který uložil záznam.';
COMMENT ON COLUMN PEV_T_PROFILE_OPTIONS.CREATED_DATE IS 'Datum vytvoření';
COMMENT ON COLUMN PEV_T_PROFILE_OPTIONS.CREATED_BY IS 'Uživatel, který vytvoril záznam.';
COMMENT ON COLUMN PEV_T_PROFILE_OPTIONS.ID IS 'PK - ID Identifikátor';
COMMENT ON COLUMN PEV_T_PROFILE_OPTIONS.CODE IS 'Kód';
COMMENT ON COLUMN PEV_T_PROFILE_OPTIONS.VALUE IS 'Hodnota';
/

