BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PEV_T_CHANGES DROP COLUMN OLD_JOURNAL_DATE';
  EXCEPTION WHEN others THEN
    null;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PEV_T_CHANGES ADD OLD_JOURNAL_DATE DATE';
  EXCEPTION WHEN others THEN
    null;
END;
/
COMMENT ON COLUMN PEV_T_CHANGES.OLD_JOURNAL_DATE IS 'previous last date of journal change';
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PEV_T_CHANGES DROP COLUMN JOURNAL_DATE';
  EXCEPTION WHEN others THEN
    null;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PEV_T_CHANGES ADD JOURNAL_DATE DATE';
  EXCEPTION WHEN others THEN
    null;
END;
/
COMMENT ON COLUMN PEV_T_CHANGES.JOURNAL_DATE IS 'date of last change journal ';
/