BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PEV_T_PROJECTS DROP COLUMN IS_DUPLICATED';
  EXCEPTION WHEN others THEN
    null;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PEV_T_PROJECTS ADD IS_DUPLICATED NUMBER DEFAULT NULL';
  EXCEPTION WHEN others THEN
    null;
END;
/
COMMENT ON COLUMN PEV_T_PROJECTS.IS_DUPLICATED IS 'Jesli vyšel z kopie 1-ano, 2 byl zaslan mail';
/
