  GRANT SELECT ON "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER" TO "CEOS_INTRADM" WITH GRANT OPTION
  /
  GRANT INSERT ON "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER" TO "CEOS_INTRADM" WITH GRANT OPTION
  /
  GRANT UPDATE ON "CEOS_INTRADM_BL"."PEV_T_LOVE_REMIDER" TO "CEOS_INTRADM" WITH GRANT OPTION
  /
  GRANT DELETE ON "CEOS_INTRADM_BL"."pev_t_love_remider" TO "CEOS_INTRADM" WITH GRANT OPTION
  /