  GRANT SELECT ON "CEOS_INTRADM_BL"."PEV_T_NOTE_REMIDER_LOG" TO "CEOS_INTRADM" WITH GRANT OPTION
  /
  GRANT INSERT ON "CEOS_INTRADM_BL"."PEV_T_NOTE_REMIDER_LOG" TO "CEOS_INTRADM" WITH GRANT OPTION
  /
  GRANT UPDATE ON "CEOS_INTRADM_BL"."PEV_T_NOTE_REMIDER_LOG" TO "CEOS_INTRADM" WITH GRANT OPTION
  /
  GRANT DELETE ON "CEOS_INTRADM_BL"."PEV_T_NOTE_REMIDER_LOG" TO "CEOS_INTRADM" WITH GRANT OPTION
  /