GRANT READ ON "CEOS_INTRADM_BL"."PEV_T_FILES" TO "RL_CEOS_INTRADM_BL_RO";
GRANT READ ON "CEOS_INTRADM_BL"."PEV_T_LOV_PEOPLE_POSITION" TO "RL_CEOS_INTRADM_BL_RO";
GRANT READ ON "CEOS_INTRADM_BL"."PEV_T_LOV_PROJECT_IDENTIFY" TO "RL_CEOS_INTRADM_BL_RO";
GRANT READ ON "CEOS_INTRADM_BL"."PEV_T_LOV_PROJECT_STATE" TO "RL_CEOS_INTRADM_BL_RO";
GRANT READ ON "CEOS_INTRADM_BL"."PEV_T_LOV_PROJECT_STATUS" TO "RL_CEOS_INTRADM_BL_RO";
--GRANT READ ON "CEOS_INTRADM_BL"."PEV_T_PEOPLE_POSITIONS" TO "RL_CEOS_INTRADM_BL_RO";
GRANT READ ON "CEOS_INTRADM_BL"."PEV_T_PEOPLES" TO "RL_CEOS_INTRADM_BL_RO";
GRANT READ ON "CEOS_INTRADM_BL"."PEV_T_PROJECT_DEVELOPER" TO "RL_CEOS_INTRADM_BL_RO";
GRANT READ ON "CEOS_INTRADM_BL"."PEV_T_PROJECTS" TO "RL_CEOS_INTRADM_BL_RO";
/
